spring:
  datasource:
    url: jdbc:mysql://localhost:3306/powerstaff?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Berlin
    username: powerstaff
    password: powerstaff
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

  ai:
    model:
      #chat: "ollama"
      chat: "openai"

    mcp:
      client:
        streamable-http:
          connections:
            lucene-search:
             url: http://localhost:11000
             endpoint: /mcp/message

    openai:
      base-url: http://localhost:1234
      api-key: "dummy"
      chat:
        options:
          model: qwen/qwen3-14b
          temperature: 0.7
          stream-usage: true
    #ollama:
    #  base-url: http://localhost:11434
    #  init:
    #    pull-model-strategy: always
    #    timeout: 60s
    #    max-retries: 1
    #  chat:
    #    options:
    #      model: qwen3.5:4b

# Logging – Entwicklung
logging:
  level:
    de.mirkosertic.powerstaff: DEBUG
    org.springframework: INFO
    org.springframework.jdbc.core: DEBUG
    org.springframework.security: TRACE
    root: INFO

server:
  servlet:
    session:
      cookie:
        secure: false
        same-site: lax
