#!/bin/bash
set -e

# Docs screenshot startup script (Dev-Mode, kein JaCoCo)
# Generated by Maven Resources Plugin with filtering during pre-integration-test phase
# Usage: ./start-docs.sh [PORT]

PORT="${1:-8200}"
JAR="@project.build.directory@/@project.build.finalName@.jar"
PID_FILE="@project.build.directory@/docs-app.pid"

# Validation
if [ ! -f "$JAR" ]; then
  echo "ERROR: JAR not found at $JAR" >&2
  exit 1
fi

# Forward SIGTERM/SIGINT to the JVM so it shuts down cleanly.
cleanup() {
  if [ -n "$APP_PID" ]; then
    kill -TERM "$APP_PID" 2>/dev/null || true
    wait "$APP_PID" 2>/dev/null || true
  fi
  rm -f "$PID_FILE"
}
trap cleanup TERM INT

# Start JVM with dev mode enabled (realistic seed data, no JaCoCo overhead).
java \
  -Dspring.profiles.active=e2e \
  -Ddevmode=true \
  -Dserver.port="$PORT" \
  -jar "$JAR" &

APP_PID=$!
echo "$APP_PID" > "$PID_FILE"

# Block until the JVM exits.
wait "$APP_PID"
