#!/bin/bash
set -e

# E2E JAR startup script with JaCoCo coverage agent
# Generated by Maven Resources Plugin with filtering during pre-integration-test phase
# Usage: ./start-e2e-with-jacoco.sh [PORT]

PORT="${1:-8100}"
JAR="@project.build.directory@/@project.build.finalName@.jar"
JACOCO_AGENT="@settings.localRepository@/org/jacoco/org.jacoco.agent/@jacoco.version@/org.jacoco.agent-@jacoco.version@-runtime.jar"
JACOCO_EXEC="@project.build.directory@/jacoco-e2e.exec"

# Validation
if [ ! -f "$JAR" ]; then
  echo "ERROR: JAR not found at $JAR" >&2
  exit 1
fi

if [ ! -f "$JACOCO_AGENT" ]; then
  echo "ERROR: JaCoCo agent not found at $JACOCO_AGENT" >&2
  exit 1
fi

# Start Spring Boot with JaCoCo agent
exec java \
  -javaagent:"$JACOCO_AGENT=destfile=$JACOCO_EXEC" \
  -Dspring.profiles.active=e2e \
  -Dserver.port="$PORT" \
  -jar "$JAR"
